//! LUKS1 passphrase verifier for the Tails 0.20.1 persistence partition.
//!
//! Re-implements the cryptsetup LUKS1 key-slot unlocking algorithm so it can
//! run entirely in the browser via WebAssembly:
//!
//!   PBKDF2-HMAC-SHA1(passphrase, slot.salt, slot.iterations) -> derived key
//!   AES-256-CBC with ESSIV:sha256 (IV = AES-ECB(SHA256(key), LE64(sector)||0))
//!   anti-forensic merge (XOR + SHA1 diffusion)
//!   PBKDF2-HMAC-SHA1(master_key, mk_digest_salt, mk_digest_iter) == mk-digest
//!
//! The target header is embedded at compile time and pointed at
//! `01_CRACKING_TARGET/myluksdrive-luks-header`.

mod utils;

use aes::cipher::{generic_array::GenericArray, BlockEncrypt, KeyInit};
use aes::Aes256;
use cbc::cipher::{block_padding::NoPadding, BlockDecryptMut, BlockEncryptMut, KeyIvInit};
use cbc::{Decryptor, Encryptor};
use hmac::Hmac;
use pbkdf2::pbkdf2;
use serde::Serialize;
use sha1::Sha1;
use sha2::{Digest, Sha256};
use wasm_bindgen::prelude::*;

/// The real LUKS1 header extracted from the target USB image.
static LUKS_HEADER: &[u8] = include_bytes!("../../01_CRACKING_TARGET/myluksdrive-luks-header");
/// Synthetic LUKS1 header generated by `tools/gen_test_luks.py` (passphrase "testpass").
static TEST_HEADER: &[u8] = include_bytes!("../tests/fixtures/test-luks-header.bin");

fn target_header(target: &str) -> &'static [u8] {
    match target {
        "test" => TEST_HEADER,
        _ => LUKS_HEADER,
    }
}

const LUKS_MAGIC: &[u8; 6] = b"LUKS\xba\xbe";
const LUKS_KEY_ENABLED: u32 = 0x00AC71F3;
const LUKS_SALTSIZE: usize = 32;
const LUKS_DIGESTSIZE: usize = 20;
const SECTOR_SIZE: usize = 512;
const SLOTS: usize = 8;

#[derive(Clone, Serialize)]
pub struct KeySlotInfo {
    pub active: bool,
    pub iterations: u32,
    pub salt_hex: String,
    pub key_material_offset: u32,
    pub stripes: u32,
}

#[derive(Clone, Serialize)]
pub struct LuksInfo {
    pub version: u16,
    pub cipher_name: String,
    pub cipher_mode: String,
    pub hash_spec: String,
    pub payload_offset: u32,
    pub key_bytes: u32,
    pub mk_digest_hex: String,
    pub mk_digest_salt_hex: String,
    pub mk_digest_iterations: u32,
    pub uuid: String,
    pub slots: Vec<KeySlotInfo>,
}

fn be16(b: &[u8], off: usize) -> u16 {
    u16::from_be_bytes([b[off], b[off + 1]])
}

fn be32(b: &[u8], off: usize) -> u32 {
    u32::from_be_bytes([b[off], b[off + 1], b[off + 2], b[off + 3]])
}

fn cstring(b: &[u8], off: usize, len: usize) -> String {
    let end = b[off..off + len]
        .iter()
        .position(|&c| c == 0)
        .unwrap_or(len);
    String::from_utf8_lossy(&b[off..off + end]).to_string()
}

/// Parse a LUKS1 header (first 592 bytes + key-slot table).
pub fn luks1_parse(header: &[u8]) -> Result<LuksInfo, String> {
    if header.len() < 592 {
        return Err("Header too short".to_string());
    }
    if &header[0..6] != LUKS_MAGIC {
        return Err("Not a valid LUKS1 header".to_string());
    }
    let version = be16(header, 6);
    if version != 1 {
        return Err(format!("Unsupported LUKS version: {}", version));
    }

    let cipher_name = cstring(header, 8, 32);
    let cipher_mode = cstring(header, 40, 32);
    let hash_spec = cstring(header, 72, 32);
    let payload_offset = be32(header, 104);
    let key_bytes = be32(header, 108);
    let mk_digest = &header[112..112 + LUKS_DIGESTSIZE];
    let mk_digest_salt = &header[132..132 + LUKS_SALTSIZE];
    let mk_digest_iterations = be32(header, 164);
    let uuid = cstring(header, 168, 40);

    let mut slots = Vec::with_capacity(SLOTS);
    for i in 0..SLOTS {
        let off = 208 + i * 48;
        slots.push(KeySlotInfo {
            active: be32(header, off) == LUKS_KEY_ENABLED,
            iterations: be32(header, off + 4),
            salt_hex: hex::encode(&header[off + 8..off + 40]),
            key_material_offset: be32(header, off + 40),
            stripes: be32(header, off + 44),
        });
    }

    Ok(LuksInfo {
        version,
        cipher_name,
        cipher_mode,
        hash_spec,
        payload_offset,
        key_bytes,
        mk_digest_hex: hex::encode(mk_digest),
        mk_digest_salt_hex: hex::encode(mk_digest_salt),
        mk_digest_iterations,
        uuid,
        slots,
    })
}

/// PBKDF2-HMAC-SHA1 (used both for passphrase->key and master-key digest).
pub fn derive_key_sha1(pass: &[u8], salt: &[u8], iterations: u32, out: &mut [u8]) {
    let _ = pbkdf2::<Hmac<Sha1>>(pass, salt, iterations, out);
}

fn sha256(data: &[u8]) -> [u8; 32] {
    let mut h = Sha256::new();
    h.update(data);
    h.finalize().into()
}

/// cryptsetup's `hash_buf`: dst = SHA1( BE32(iv) || src[..len] )[..len]
fn hash_buf(src: &[u8], iv: u32, len: usize) -> Vec<u8> {
    let mut h = Sha1::new();
    h.update(iv.to_be_bytes());
    h.update(&src[..len]);
    h.finalize()[..len].to_vec()
}

/// cryptsetup's `diffuse` (SHA1-based information spreading).
pub fn diffuse(src: &[u8], size: usize) -> Vec<u8> {
    const DIGEST_SIZE: usize = LUKS_DIGESTSIZE; // sha1 => 20
    let mut dst = vec![0u8; size];
    let blocks = size / DIGEST_SIZE;
    let padding = size % DIGEST_SIZE;
    for i in 0..blocks {
        let d = hash_buf(&src[DIGEST_SIZE * i..], i as u32, DIGEST_SIZE);
        dst[DIGEST_SIZE * i..DIGEST_SIZE * i + DIGEST_SIZE].copy_from_slice(&d);
    }
    if padding > 0 {
        let i = blocks;
        let d = hash_buf(&src[DIGEST_SIZE * i..], i as u32, padding);
        dst[DIGEST_SIZE * i..DIGEST_SIZE * i + padding].copy_from_slice(&d);
    }
    dst
}

/// Anti-forensic split (inverse of `af_merge`).
pub fn af_split(master: &[u8], stripes: u32) -> Vec<u8> {
    let blocksize = master.len();
    let stripes = stripes as usize;
    let mut dst = vec![0u8; blocksize * stripes];
    let mut buf = vec![0u8; blocksize];
    let mut rng: u64 = 0x9E3779B97F4A7C15;
    for i in 0..stripes - 1 {
        let mut stripe = vec![0u8; blocksize];
        for b in stripe.iter_mut() {
            rng = rng
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            *b = (rng >> 33) as u8;
        }
        dst[blocksize * i..blocksize * (i + 1)].copy_from_slice(&stripe);
        for j in 0..blocksize {
            buf[j] ^= stripe[j];
        }
        buf = diffuse(&buf, blocksize);
    }
    for j in 0..blocksize {
        dst[blocksize * (stripes - 1) + j] = master[j] ^ buf[j];
    }
    dst
}

/// Anti-forensic merge (recovers the master key from the stripes).
pub fn af_merge(src: &[u8], blocksize: usize, stripes: u32) -> Vec<u8> {
    let stripes = stripes as usize;
    let mut buf = vec![0u8; blocksize];
    for i in 0..stripes - 1 {
        let stripe = &src[blocksize * i..blocksize * (i + 1)];
        for j in 0..blocksize {
            buf[j] ^= stripe[j];
        }
        buf = diffuse(&buf, blocksize);
    }
    let last = &src[blocksize * (stripes - 1)..blocksize * stripes];
    let mut dst = vec![0u8; blocksize];
    for j in 0..blocksize {
        dst[j] = last[j] ^ buf[j];
    }
    dst
}

/// ESSIV IV = AES-256-ECB_encrypt(SHA256(key), LE64(sector) || 0x00*8).
fn essiv_iv(essiv: &Aes256, sector: u64) -> [u8; 16] {
    let mut block = [0u8; 16];
    block[..8].copy_from_slice(&sector.to_le_bytes());
    let mut g = GenericArray::clone_from_slice(&block);
    essiv.encrypt_block(&mut g);
    let mut out = [0u8; 16];
    out.copy_from_slice(&g);
    out
}

/// Decrypt key material in place (AES-256-CBC, one ESSIV IV per 512-byte sector).
pub fn decrypt_key_material(data: &mut [u8], key: &[u8; 32]) {
    let essiv = Aes256::new(GenericArray::from_slice(&sha256(key)));
    let sectors = data.len() / SECTOR_SIZE;
    for j in 0..sectors {
        let iv = essiv_iv(&essiv, j as u64);
        let dec = Decryptor::<Aes256>::new_from_slices(key, &iv).expect("key/iv length");
        let _ = dec
            .decrypt_padded_mut::<NoPadding>(&mut data[j * SECTOR_SIZE..(j + 1) * SECTOR_SIZE])
            .expect("sector length multiple of block size");
    }
}

/// Encrypt key material in place (used by the synthetic round-trip test).
pub fn encrypt_key_material(data: &mut [u8], key: &[u8; 32]) {
    let essiv = Aes256::new(GenericArray::from_slice(&sha256(key)));
    let sectors = data.len() / SECTOR_SIZE;
    for j in 0..sectors {
        let iv = essiv_iv(&essiv, j as u64);
        let enc = Encryptor::<Aes256>::new_from_slices(key, &iv).expect("key/iv length");
        let _ = enc
            .encrypt_padded_mut::<NoPadding>(
                &mut data[j * SECTOR_SIZE..(j + 1) * SECTOR_SIZE],
                SECTOR_SIZE,
            )
            .expect("sector length multiple of block size");
    }
}

/// Check whether a recovered master key matches the header's mk-digest.
pub fn master_key_digest_matches(info: &LuksInfo, master: &[u8]) -> Result<bool, String> {
    let mk_salt = hex::decode(&info.mk_digest_salt_hex)
        .map_err(|_| "Invalid verification salt".to_string())?;
    let mk_digest = hex::decode(&info.mk_digest_hex).map_err(|_| "Invalid digest".to_string())?;
    let mut check = vec![0u8; LUKS_DIGESTSIZE];
    derive_key_sha1(master, &mk_salt, info.mk_digest_iterations, &mut check);
    Ok(check == mk_digest)
}

/// Try to unlock every active key slot with `passphrase`.
///
/// Returns `Ok((slot_index, master_key))` on success or `Err(reason)`.
pub fn luks1_verify(header: &[u8], passphrase: &str) -> Result<(usize, Vec<u8>), String> {
    let info = luks1_parse(header)?;

    if info.cipher_name != "aes" || info.key_bytes != 32 {
        return Err(format!(
            "Unsupported cipher: {}-{} ({} bytes)",
            info.cipher_name, info.cipher_mode, info.key_bytes
        ));
    }
    if info.cipher_mode != "cbc-essiv:sha256" {
        return Err(format!("Unsupported cipher mode: {}", info.cipher_mode));
    }
    if info.hash_spec != "sha1" {
        return Err(format!("Unsupported hash: {}", info.hash_spec));
    }

    let key_bytes = info.key_bytes as usize;
    let mut derived = vec![0u8; key_bytes];

    for (slot_idx, slot) in info.slots.iter().enumerate() {
        if !slot.active || slot.stripes == 0 {
            continue;
        }

        let af_size =
            ((key_bytes * slot.stripes as usize + SECTOR_SIZE - 1) / SECTOR_SIZE) * SECTOR_SIZE;
        let offset = slot.key_material_offset as usize * SECTOR_SIZE;
        let end = offset + af_size;
        if end > header.len() {
            return Err("Incomplete header (missing key material)".to_string());
        }

        let salt = hex::decode(&slot.salt_hex).map_err(|_| "Invalid salt".to_string())?;
        derive_key_sha1(passphrase.as_bytes(), &salt, slot.iterations, &mut derived);

        let mut key = [0u8; 32];
        key.copy_from_slice(&derived);

        let mut material = header[offset..end].to_vec();
        decrypt_key_material(&mut material, &key);
        let master = af_merge(&material, key_bytes, slot.stripes);

        if master_key_digest_matches(&info, &master)? {
            return Ok((slot_idx, master));
        }
    }

    Err("Incorrect passphrase".to_string())
}

#[derive(Serialize)]
struct VerifyResult {
    success: bool,
    error: Option<String>,
    master_key_hex: Option<String>,
    slot: Option<usize>,
    uuid: Option<String>,
    iterations: Option<u32>,
}

#[wasm_bindgen]
pub fn luks_verify_wasm(target: String, passphrase: String) -> String {
    let header = target_header(&target);
    match luks1_verify(header, &passphrase) {
        Ok((slot, master)) => {
            let info = luks1_parse(header).ok();
            serde_json::to_string(&VerifyResult {
                success: true,
                error: None,
                master_key_hex: Some(hex::encode(&master)),
                slot: Some(slot),
                uuid: info.as_ref().map(|i| i.uuid.clone()),
                iterations: info
                    .as_ref()
                    .and_then(|i| i.slots.get(slot))
                    .map(|s| s.iterations),
            })
            .unwrap_or_else(|e| format!(r#"{{"success":false,"error":"{}"}}"#, e))
        }
        Err(e) => serde_json::to_string(&VerifyResult {
            success: false,
            error: Some(e),
            master_key_hex: None,
            slot: None,
            uuid: None,
            iterations: None,
        })
        .unwrap(),
    }
}

#[wasm_bindgen]
pub fn luks_info_wasm(target: String) -> String {
    let header = target_header(&target);
    match luks1_parse(header) {
        Ok(info) => {
            serde_json::to_string(&info).unwrap_or_else(|e| format!(r#"{{"error":"{}"}}"#, e))
        }
        Err(e) => format!(r#"{{"error":"{}"}}"#, e),
    }
}

/// Independently verify a recovered master key (32 bytes, hex) against the
/// header's mk-digest, without needing the passphrase.
#[wasm_bindgen]
pub fn luks_verify_master_key_wasm(target: String, master_key_hex: String) -> String {
    #[derive(Serialize)]
    struct MkResult {
        success: bool,
        error: Option<String>,
    }

    let info = match luks1_parse(target_header(&target)) {
        Ok(i) => i,
        Err(e) => {
            return serde_json::to_string(&MkResult {
                success: false,
                error: Some(e),
            })
            .unwrap();
        }
    };

    let master = match hex::decode(master_key_hex.trim()) {
        Ok(m) if m.len() == info.key_bytes as usize => m,
        Ok(_) => {
            return serde_json::to_string(&MkResult {
                success: false,
                error: Some(format!(
                    "Master key must be {} bytes ({}-char hex)",
                    info.key_bytes,
                    info.key_bytes as usize * 2
                )),
            })
            .unwrap();
        }
        Err(_) => {
            return serde_json::to_string(&MkResult {
                success: false,
                error: Some("Invalid hex".to_string()),
            })
            .unwrap();
        }
    };

    match master_key_digest_matches(&info, &master) {
        Ok(true) => serde_json::to_string(&MkResult {
            success: true,
            error: None,
        })
        .unwrap(),
        Ok(false) => serde_json::to_string(&MkResult {
            success: false,
            error: Some("Master key does NOT match the header digest".to_string()),
        })
        .unwrap(),
        Err(e) => serde_json::to_string(&MkResult {
            success: false,
            error: Some(e),
        })
        .unwrap(),
    }
}

#[wasm_bindgen(start)]
pub fn start() {
    utils::set_panic_hook();
}




