use luksdecrypter::*;

const REAL_HEADER: &[u8] = include_bytes!("../../01_CRACKING_TARGET/myluksdrive-luks-header");
const FIXTURE: &[u8] = include_bytes!("fixtures/test-luks-header.bin");

/// PBKDF2-HMAC-SHA1 known vector (RFC 6070 / widely published).
#[test]
fn test_pbkdf2_sha1_known_vector() {
    let mut out = [0u8; 20];
    derive_key_sha1(b"password", b"salt", 1, &mut out);
    assert_eq!(hex::encode(out), "0c60c80f961f0e71f3a9b524af6012062fe037a6");
}

fn write_cstring(buf: &mut [u8], off: usize, size: usize, text: &str) {
    let raw = text.as_bytes();
    assert!(raw.len() <= size);
    buf[off..off + raw.len()].copy_from_slice(raw);
}

/// Build a synthetic LUKS1 header (single active slot) with a known passphrase.
fn build_test_header(master_key: &[u8], passphrase: &str) -> Vec<u8> {
    const KEY_BYTES: u32 = 32;
    const STRIPES: u32 = 4000;
    const KM_OFFSET: u32 = 8;
    const PAYLOAD_OFFSET: u32 = 2056;
    let slot_salt = [0x11u8; 32];
    let mk_salt = [0x22u8; 32];
    let slot_iters: u32 = 1000;
    let mk_iters: u32 = 1000;

    let mut derived = [0u8; 32];
    derive_key_sha1(passphrase.as_bytes(), &slot_salt, slot_iters, &mut derived);

    let mut material = af_split(master_key, STRIPES);
    encrypt_key_material(&mut material, &derived);

    let mut mk_digest = [0u8; 20];
    derive_key_sha1(master_key, &mk_salt, mk_iters, &mut mk_digest);

    let mut h = vec![0u8; PAYLOAD_OFFSET as usize * 512];
    h[0..6].copy_from_slice(b"LUKS\xba\xbe");
    h[6..8].copy_from_slice(&1u16.to_be_bytes());
    write_cstring(&mut h, 8, 32, "aes");
    write_cstring(&mut h, 40, 32, "cbc-essiv:sha256");
    write_cstring(&mut h, 72, 32, "sha1");
    h[104..108].copy_from_slice(&PAYLOAD_OFFSET.to_be_bytes());
    h[108..112].copy_from_slice(&KEY_BYTES.to_be_bytes());
    h[112..132].copy_from_slice(&mk_digest);
    h[132..164].copy_from_slice(&mk_salt);
    h[164..168].copy_from_slice(&mk_iters.to_be_bytes());
    write_cstring(&mut h, 168, 40, "11111111-2222-3333-4444-555555555555");

    let off = 208; // keyslot 0
    h[off..off + 4].copy_from_slice(&0x00AC71F3u32.to_be_bytes());
    h[off + 4..off + 8].copy_from_slice(&slot_iters.to_be_bytes());
    h[off + 8..off + 40].copy_from_slice(&slot_salt);
    h[off + 40..off + 44].copy_from_slice(&KM_OFFSET.to_be_bytes());
    h[off + 44..off + 48].copy_from_slice(&STRIPES.to_be_bytes());

    let km = KM_OFFSET as usize * 512;
    h[km..km + material.len()].copy_from_slice(&material);
    h
}

/// Full round-trip: split+encrypt a synthetic header, then unlock it.
#[test]
fn test_roundtrip_synthetic_header() {
    let passphrase = "correct horse battery staple";
    let master_key: Vec<u8> = (0..32u8).collect();

    let header = build_test_header(&master_key, passphrase);

    let (slot, recovered) = luks1_verify(&header, passphrase).expect("should unlock");
    assert_eq!(slot, 0);
    assert_eq!(recovered, master_key);

    assert!(luks1_verify(&header, "wrong passphrase").is_err());
}

/// Cross-language check: the fixture was generated by an independent Python
/// implementation (tools/gen_test_luks.py) and must unlock here too.
#[test]
fn test_python_fixture_unlocks() {
    let (slot, master) = luks1_verify(FIXTURE, "testpass").expect("fixture should unlock");
    assert_eq!(slot, 0);
    let expected: Vec<u8> = (0..32u8).collect();
    assert_eq!(master, expected);
    assert!(luks1_verify(FIXTURE, "nope").is_err());
}

/// The real target header must parse to the known values and must not produce a
/// false positive for a wrong passphrase.
#[test]
fn test_real_target_parse_and_reject() {
    let info = luks1_parse(REAL_HEADER).expect("real header should parse");

    assert_eq!(info.version, 1);
    assert_eq!(info.uuid, "55645f1a-f8fd-490f-b3e4-862dddde4e08");
    assert_eq!(info.cipher_name, "aes");
    assert_eq!(info.cipher_mode, "cbc-essiv:sha256");
    assert_eq!(info.hash_spec, "sha1");
    assert_eq!(info.key_bytes, 32);
    assert_eq!(info.payload_offset, 2056);
    assert_eq!(info.mk_digest_iterations, 34000);
    assert_eq!(
        info.mk_digest_hex,
        "954d9452180e8ff5ffe851eac1c07e32b41a995f"
    );
    assert_eq!(
        info.mk_digest_salt_hex,
        "adcd0072bfb0c15a8a0e587fbc2d2b79678158f5b05144a5ff2122413253caba"
    );

    // Only slot 0 is active, iterations 105474, key material at sector 8.
    let active: Vec<usize> = info
        .slots
        .iter()
        .enumerate()
        .filter(|(_, s)| s.active)
        .map(|(i, _)| i)
        .collect();
    assert_eq!(active, vec![0]);
    assert_eq!(info.slots[0].iterations, 105474);
    assert_eq!(info.slots[0].stripes, 4000);
    assert_eq!(info.slots[0].key_material_offset, 8);
    assert_eq!(
        info.slots[0].salt_hex,
        "423f02606d9df6725149a3d2f623d236beab3db29bb82a40cf6e543526dec564"
    );

    assert!(luks1_verify(REAL_HEADER, "this-is-definitely-not-the-passphrase").is_err());
}
